FROM node:6.11.1-alpine
ARG NPM_TOKEN
COPY src/package.json src/.npmrc /tmp/
COPY .cache /tmp/node_modules
RUN cd /tmp && npm i && mkdir -p /usr/src
WORKDIR /usr/src
COPY src/lib /usr/src/lib
COPY src/mocks /usr/src/mocks
COPY src/test /usr/src/test
COPY src/nodemon.json src/package.json src/webpack.client.js src/webpack.server.js /usr/src/
EXPOSE 80 81
CMD ln -s /tmp/node_modules ./node_modules && echo '127.0.0.1 api' >> /etc/hosts && ./node_modules/.bin/standard && ./node_modules/.bin/mocha --recursive test
