version: '2'
services:
  web:
    image: nudj/web:latest
    env_file: env
    depends_on:
      - api
    ports:
      - "80:80"
  api:
    image: nudj/api:latest
    depends_on:
      - db
    ports:
      - "81:81"
  db:
    image: arangodb
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - dbdata:/var/lib/arangodb
    ports:
      - "8529:8529"
    command: arangod --server.authentication false
volumes:
  dbdata:
