FROM node:6.10.0-alpine
RUN mkdir -p /usr/www
WORKDIR /usr/www
COPY package.json /usr/www/package.json
RUN npm i
COPY src /usr/www/src
COPY test /usr/www/test
RUN ./node_modules/.bin/webpack --config ./src/webpack.client.js --bail --hide-modules && ./node_modules/.bin/webpack --config ./src/webpack.server.js --bail --hide-modules
EXPOSE 3000
CMD ./node_modules/.bin/standard && ./node_modules/.bin/mocha test/*.js
